
version: "3.9"
services:
  web:
    build: .
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    environment:
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
    ports:
      - "8000:8000"
#"gunicorn", "-w", "3", "-b", ":8000", "hello_django.wsgi:application"



